name: Deploy documentation

on: 
  workflow_dispatch:

jobs:
  deploy_documentation:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: simonbs/runestone
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        ref: main
        path: runestone
        submodules: recursive
    - name: Generate documentation
      run: |
          cd runestone
          xcodebuild docbuild -scheme Runestone -destination 'platform=iOS Simulator,name=iPhone 13' -derivedDataPath ../DerivedData
          mv DerivedData/Products/Debug-iphonesimulator/Runestone.doccarchive Runestone.doccarchive
    - name: Commit changes
      run: |
         if [ -n "$(git status --porcelain)" ]; then
           git add Runestone.doccarchive
           git commit -S -am "Generated documentation"
           git push
         else
           echo "No changes to commit"
         fi
