name: Deploy documentation

on: 
  workflow_dispatch:

jobs:
  fetch-lokalise:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: simonbs/runestone
        ref: main
