name: Deploy documentation

on: 
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag or to generate documentation for
        default: main
        required: true

jobs:
  deploy_documentation:
    runs-on: macos-11
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout Runestone repository
      uses: actions/checkout@v2
        with:
          repository: simonbs/runestone
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.event.inputs.tag }}
          path: runestone
          submodules: recursive
    - name: Generate documentation
      run: |
          cd runestone
          xcodebuild docbuild -scheme Runestone -destination 'platform=iOS Simulator,name=iPhone 13' -derivedDataPath ../DerivedData
          rm -rf ../Runestone.doccarchive
          mv ../DerivedData/Build/Products/Debug-iphonesimulator/Runestone.doccarchive ../
    - name: Setup GPG key
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git-user-signingkey: true
        git-commit-gpgsign: true
    - name: Commit changes
      run: |
         if [ -n "$(git status --porcelain)" ]; then
           git add Runestone.doccarchive
           git commit -S -m "Updates documentation"
           git push
         else
           echo "No changes to commit"
         fi
