name: Deploy documentation

on: 
  workflow_dispatch:

jobs:
  deploy_documentation:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: simonbs/runestone
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        ref: main
        path: runestone
    - name: Debug
      run: ls -la
    - name: Navigate to Runestone repository
      run: cd runestone
    - name: Generate documentation
      run: xcodebuild docbuild -scheme Runestone -destination 'platform=iOS Simulator,name=iPhone 13' -derivedDataPath ../DerivedData
    - name: Navigate back to root
      run: cd ..
    - name: Copy documentation
      run: mv DerivedData/Products/Debug-iphonesimulator/Runestone.doccarchive Runestone.doccarchive
    - name: Stage changes
      run: |
         if [ -n "$(git status --porcelain)" ]; then
           git add Runestone.doccarchive
           exit 1
         else
           echo "No changes to stage"
         fi
    - name: Commit changes
      run: |
         if [ -n "$(git status --porcelain)" ]; then
           git commit -S -am "Generated documentation"
           git push
           exit 1
         else
           echo "No changes to commit"
         fi
